name: Python CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build: # we can name it with any name we want
    runs-on: ubuntu-latest

    steps:
        #Step 1: Check out the code from repo
      - uses: actions/checkout@v4

      #Step 2: Set up python env
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
            python-version: '3.8'

      #Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    #Step 4: Run tests
      - name: Run tests
        run: pytest   
